apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name .Values.mysql.db.type }}
  labels:
  {{- include "wordpress.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.mysql.service.port }}
  selector:
  {{- include "mysql.selectorLabels" . | nindent 4 }}
  clusterIP: None