apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Values.mysql.db.type "pass" }}
type: Opaque
data:
  {{- if .Values.mysql.db.password }}
  password: {{ default "" .Values.mysql.db.password | b64enc }}
  {{- else }}
  password: {{ randAlphaNum 10 | b64enc }}
  {{- end }}