apiVersion: v1
kind: Service
metadata:
  name: bookstack
  labels:
    app: bookstack
    tier: frontend
spec:
  selector:
    app: bookstack
  ports:
    - port: 8080
      targetPort: 80
  type: NodePort
